# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x05image\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\" \n\x0eStringResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2E\n\x0cImageService\x12\x35\n\x05hello\x12\x13.image.ImageRequest\x1a\x15.image.StringResponse\"\x00\x42&\n\x16\x63om.dawnop.image.protoB\nImageProtoP\x00\x62\x06proto3')



_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_STRINGRESPONSE = DESCRIPTOR.message_types_by_name['StringResponse']
ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), {
  'DESCRIPTOR' : _STRINGRESPONSE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.StringResponse)
  })
_sym_db.RegisterMessage(StringResponse)

_IMAGESERVICE = DESCRIPTOR.services_by_name['ImageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.dawnop.image.protoB\nImageProtoP\000'
  _IMAGEREQUEST._serialized_start=22
  _IMAGEREQUEST._serialized_end=51
  _STRINGRESPONSE._serialized_start=53
  _STRINGRESPONSE._serialized_end=85
  _IMAGESERVICE._serialized_start=87
  _IMAGESERVICE._serialized_end=156
# @@protoc_insertion_point(module_scope)
